### ISSUE TITLE
Upgrade from Boundless Suite 4.9 to 4.10

### ISSUE THREAD

**Issue by sindile** [mxabierto/docker-boundless-suite#1]
I saw that the Dockerfile refers to Boundless Suite 4.9

Is there going to be a Boundless Suite 4.10 (it is available from Boundless if you are a paying customer)

If not, is there a work flow you might suggest I follow.

**Comment by leodc** [comment]
Hello @sindile !

As you say Boundless Suite 4.10 is only available for paying customers. This deploy is focused on the "non-paying" version of boundless. 

If you have your credentials as paid customer, I think the easy way will be to create a Dockerfile following the package installation instructions from the guide: https://connect.boundlessgeo.com/docs/suite/enterprise/latest/install/ubuntu/packages.html

Or if you have direct links to dowload your paid version you could replace it in the Dockerfile instruction:

`RUN git clone https://github.com/mxabierto/docker-boundless-suite suite \
  && wget -q https://github.com/mxabierto/boundless-suite/releases/download/4.9.1/BoundlessSuite-4.9.1-war.zip -O boundless.zip \
&& wget -q https://github.com/mxabierto/boundless-suite/releases/download/4.9.1/BoundlessSuite-4.9.1-ext.zip -O boundless-ext.zip`
